
import java.awt.Color;
import static java.lang.System.exit;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dcL
 */
public class criminalGroups extends javax.swing.JFrame {

    /**
     * Creates new form criminalGroups
     */
    public criminalGroups() {
        initComponents();
    }
    Dbconnect con;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnhom = new javax.swing.JButton();
        btncri = new javax.swing.JButton();
        btnnar = new javax.swing.JButton();
        btnime = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtser = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnshw = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 109, 240));

        btnhom.setBackground(new java.awt.Color(99, 164, 255));
        btnhom.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnhom.setForeground(new java.awt.Color(255, 255, 255));
        btnhom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/house-outline.png"))); // NOI18N
        btnhom.setText("   Home");
        btnhom.setBorder(null);
        btnhom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhomMouseExited(evt);
            }
        });
        btnhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomActionPerformed(evt);
            }
        });

        btncri.setBackground(new java.awt.Color(0, 75, 160));
        btncri.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btncri.setForeground(new java.awt.Color(255, 255, 255));
        btncri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/criminal-carrying-money-bag-at-his-back.png"))); // NOI18N
        btncri.setText("Criminal Groups");
        btncri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncriMouseExited(evt);
            }
        });
        btncri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncriActionPerformed(evt);
            }
        });

        btnnar.setBackground(new java.awt.Color(99, 164, 255));
        btnnar.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnnar.setForeground(new java.awt.Color(255, 255, 255));
        btnnar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/syringe.png"))); // NOI18N
        btnnar.setText("  Narcotics");
        btnnar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnnarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnnarMouseExited(evt);
            }
        });
        btnnar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnarActionPerformed(evt);
            }
        });

        btnime.setBackground(new java.awt.Color(99, 164, 255));
        btnime.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnime.setForeground(new java.awt.Color(255, 255, 255));
        btnime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/handcuffs.png"))); // NOI18N
        btnime.setText("Crime");
        btnime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnimeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnimeMouseExited(evt);
            }
        });
        btnime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimeActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/circular-design.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Global Crime");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnhom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btncri, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
            .addComponent(btnnar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnhom, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncri, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnime, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 109, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnifying-glass-searcher.png"))); // NOI18N

        txtser.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtser.setForeground(new java.awt.Color(0, 109, 254));
        txtser.setBorder(null);

        btnshw.setBackground(new java.awt.Color(0, 109, 240));
        btnshw.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btnshw.setForeground(new java.awt.Color(255, 255, 255));
        btnshw.setText("Search");
        btnshw.setBorder(null);
        btnshw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnshwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnshwMouseExited(evt);
            }
        });
        btnshw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshwActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 109, 254));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Group Name", "Crime Name"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(35);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtser, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnshw, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(143, 143, 143))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnshw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1281, 684));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// If we input the name of country then we can see the most notorious gangs of that country.
    private void btnshwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshwActionPerformed
      
        String ShowQuery="Select GroupName,CrimeName From grouptbl where CountryName=('"+txtser.getText().toString()+"')";
        con = new Dbconnect();
        try {
            ResultSet rs = con.ShowData(ShowQuery);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
            
        } catch (Exception ex) {
            
        }
        
        
    }//GEN-LAST:event_btnshwActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,109,240));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jButton1MouseExited

    private void btnhomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomMouseEntered
        // TODO add your handling code here:
        btnhom.setBackground(new Color(0,75,160));
    }//GEN-LAST:event_btnhomMouseEntered

    private void btnhomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhomMouseExited
        // TODO add your handling code here:
        btnhom.setBackground(new Color(99,164,255));
    }//GEN-LAST:event_btnhomMouseExited

    private void btncriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncriMouseEntered
        // TODO add your handling code here:
        btncri.setBackground(new Color(0,75,160));
    }//GEN-LAST:event_btncriMouseEntered

    private void btncriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncriMouseExited
        // TODO add your handling code here:
        btncri.setBackground(new Color(0,75,160));
    }//GEN-LAST:event_btncriMouseExited

    private void btncriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncriActionPerformed
        // TODO add your handling code here:
        criminalGroups c = new criminalGroups();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_btncriActionPerformed

    private void btnnarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnarMouseEntered
        // TODO add your handling code here:
        btnnar.setBackground(new Color(0,75,160));
    }//GEN-LAST:event_btnnarMouseEntered

    private void btnnarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnarMouseExited
        // TODO add your handling code here:
        btnnar.setBackground(new Color(99,164,255));
    }//GEN-LAST:event_btnnarMouseExited

    private void btnimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnimeMouseEntered
        // TODO add your handling code here:
        btnime.setBackground(new Color(0,75,160));
    }//GEN-LAST:event_btnimeMouseEntered

    private void btnimeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnimeMouseExited
        // TODO add your handling code here:
        btnime.setBackground(new Color(99,164,255));
    }//GEN-LAST:event_btnimeMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomActionPerformed
        // TODO add your handling code here:
        home h = new home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnhomActionPerformed

    private void btnnarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnarActionPerformed
        // TODO add your handling code here:
        narco n = new narco();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnnarActionPerformed

    private void btnimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimeActionPerformed
        // TODO add your handling code here:
        crime c = new crime();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnimeActionPerformed

    private void btnshwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshwMouseEntered
        // TODO add your handling code here:
        btnshw.setBackground(new Color(3,54,255));
    }//GEN-LAST:event_btnshwMouseEntered

    private void btnshwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshwMouseExited
        // TODO add your handling code here:
        btnshw.setBackground(new Color(0,109,240));
    }//GEN-LAST:event_btnshwMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criminalGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criminalGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criminalGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criminalGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criminalGroups().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncri;
    private javax.swing.JButton btnhom;
    private javax.swing.JButton btnime;
    private javax.swing.JButton btnnar;
    private javax.swing.JButton btnshw;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtser;
    // End of variables declaration//GEN-END:variables
}
